### ISSUE TITLE
Issue running get-names.clj

### ISSUE THREAD

**Issue by epilimic** [C4K3/minecraft-3-character-names#1]
Hello,

I've never used clojure before but figured I'd give it a shot considering your note on using the shell script version. Well I installed it on my Debian 8 machine using the apt-get package clojure1.2 and when I tried running the script after cloning the repo I got this as an output: http://pastebin.com/jmMk0kpk

Am I doing something wrong or does the script have an issue?

Thanks

**Comment by epilimic** [comment]
Well I was able to get this running under Windows 7. I would still appreciate it if you could tell me what I was doing wrong in debian, thanks!

**Comment by C4K3** [comment]
It's missing the function nthrest in Clojure 1.2. [It seems nthrest wasn't added until Clojure 1.3](http://clojuredocs.org/clojure.core/nthrest), so you'd have to run 1.4 or a newer version for it to work. From the debian package list it seems debian lets you choose between 1.2, 1.4 and 1.6, so installing one of the newer versions should work.

Alternatively you can download the latest clojure jarfile from [clojure.org](https://clojure.org/) and run the script as

```
java -cp clojure<version>.jar clojure.main get-names.clj
```

**Comment by epilimic** [comment]
Got it, thanks!
