### ISSUE TITLE
How do you run the clojure script?

### ISSUE THREAD

**Issue by flamingLion** [C4K3/minecraft-3-character-names#2]
I have no clue...

**Comment by C4K3** [comment]
I'm going to assume you're on Windows. First make sure you have a Java JDK installed (not JRE,) and also know the location of where it's installed (from what I can tell, it's usually in `C:\Program Files\Java\jdk1.x.0\bin\` where x is the version you installed). Next, [download Clojure](https://repo1.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.zip) from clojure.org, and unpack it somewhere you know where is, you're just interested in the clojure-1.8.0.jar file. Finally open your command prompt, and enter
```
"C:\the\path\to\jdk\bin\javac" -cp "C:\the\path\to\clojure-1.8.0.jar" clojure.main "C:\the\path\to\get-names.clj"
```
where obviously you replace the paths with their actual locations on your computer.

**Comment by C4K3** [comment]
If you're on Linux, it's a bit easier. Just install clojure through your package manager, and then run `clojure get-names.clj`, or perhaps `clj get-names.clj`.

**Comment by flamingLion** [comment]
ok, thank you
