### ISSUE TITLE
Post-run ??

### ISSUE THREAD

**Issue by worldwideguy** [C4K3/minecraft-3-character-names#3]
I'm on mac OS. I ran the .sh script in terminal and it took around 5 hours to complete but there was no effect. the files didn't update and it didn't create any new ones. No idea if I'm missing something or if it's broken.

**Comment by C4K3** [comment]
I don't know if it's broken, I don't use it myself, and it probably shouldn't be used at all.

What output did the script have?

**Comment by C4K3** [comment]
I've gone ahead and just removed the old bash script: 43e27febc98db8ae082ad7f744f8be1b5d794739

It's slow, places unnecessary burden on Mojang, and according to this may be unreliable.

You should use the Clojure script from now on.
